"""Writer for pytlwall-chamber-style .cfg files.

WIMBA builds pytlwall inputs in memory (Chamber/Layer/Beam via the API); for
debugging, every distinct geometry used in a run is also dumped as a readable
.cfg under <output>/pytlwall_inputs/. The chamber is written exactly as WIMBA
evaluates it: unit length and beta = 1 (per-assignment scaling by L and beta is
applied by WIMBA afterwards).
"""
from __future__ import annotations

from pathlib import Path


def _layer_lines(idx_or_name, lay):
    head = f"[{idx_or_name}]"
    thick = lay.get("thickness", lay.get("thick_m", ""))
    lines = [head,
             f"type = {lay.get('type', 'CW')}",
             f"thick_m = {thick}"]
    sigma = lay.get("sigma", lay.get("sigmaDC"))
    if sigma is not None:
        lines.append(f"sigmaDC = {sigma}")
    for src, dst in (("muinf_Hz", "muinf_Hz"), ("k_Hz", "k_Hz"),
                     ("epsr", "epsr"), ("tau", "tau"), ("RQ", "RQ")):
        if src in lay:
            lines.append(f"{dst} = {lay[src]}")
    return lines


def write_chamber_cfg(path, geometry, gamma=7000.0, length_m=1.0) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    layers = list(geometry.get("layers") or [])
    body = [f for f in layers if not f.get("boundary")]
    boundary = next((f for f in layers if f.get("boundary")), None)

    lines = [
        "; pytlwall chamber input generated by WIMBA (debug dump).",
        "; Evaluated at unit length and beta = 1; WIMBA scales each assignment",
        "; by its own length and local beta afterwards.",
        "",
        "[base_info]",
    ]
    if geometry.get("name"):
        lines.append(f"component_name = {geometry['name']}")
    lines += [f"chamber_shape = {geometry.get('shape', 'CIRCULAR')}",
              f"pipe_len_m = {length_m}",
              f"pipe_rad_m = {geometry.get('radius')}"]
    if geometry.get("hor") is not None:
        lines.append(f"pipe_hor_m = {geometry['hor']}")
    if geometry.get("ver") is not None:
        lines.append(f"pipe_ver_m = {geometry['ver']}")
    lines += ["betax = 1.0", "betay = 1.0", "",
              "[layers_info]", f"nbr_layers = {len(body)}", ""]
    for i, lay in enumerate(body):
        lines += _layer_lines(f"layer{i}", lay) + [""]
    if boundary is not None:
        lines += _layer_lines("boundary", boundary) + [""]
    lines += ["[beam_info]", f"gammarel = {gamma}", ""]
    path.write_text("\n".join(lines))
    return path


def read_chamber_cfg(path) -> dict:
    """Read a pytlwall chamber .cfg (the format of pytlwall's own examples,
    e.g. ex_CW) into WIMBA terms: geometry (with the boundary as last layer),
    betas, length, gamma and the frequency grid.

    frequency_info uses exponents: fmin/fmax are powers of ten, fstep the
    points-per-decade exponent (fstep=2 -> 100 points per decade).
    """
    import configparser

    parser = configparser.ConfigParser(inline_comment_prefixes=(";", "#"))
    if not parser.read(Path(path)):
        raise FileNotFoundError(f"pytlwall config not found: {path}")

    base = parser["base_info"] if parser.has_section("base_info") else {}
    geometry = {
        "name": base.get("component_name"),
        "shape": base.get("chamber_shape", "CIRCULAR").upper(),
        "radius": float(base["pipe_radius_m"]) if "pipe_radius_m" in base else None,
        "hor": float(base["pipe_hor_m"]) if "pipe_hor_m" in base else None,
        "ver": float(base["pipe_ver_m"]) if "pipe_ver_m" in base else None,
    }
    if geometry["radius"] is None:
        geometry["radius"] = geometry["ver"] or geometry["hor"]

    def _layer(sec, boundary=False):
        lay = {"type": sec.get("type", "CW"), "boundary": boundary}
        thick = sec.get("thick_m")
        if thick is not None:
            lay["thickness"] = thick if str(thick).lower() == "inf" else float(thick)
        elif boundary:
            lay["thickness"] = "inf"
        for k, dst in (("sigmadc", "sigma"), ("muinf_hz", "muinf_Hz"),
                       ("k_hz", "k_Hz"), ("epsr", "epsr"), ("tau", "tau"),
                       ("rq", "RQ")):
            if k in sec:
                v = sec[k]
                lay[dst] = v if str(v).lower() == "inf" else float(v)
        return lay

    layers = []
    n = int(parser["layers_info"].get("nbr_layers", 0))         if parser.has_section("layers_info") else 0
    for i in range(n):
        layers.append(_layer(parser[f"layer{i}"]))
    if parser.has_section("boundary"):
        layers.append(_layer(parser["boundary"], boundary=True))
    geometry["layers"] = layers

    out = {"geometry": geometry,
           "betax": float(base.get("betax", 1.0)),
           "betay": float(base.get("betay", 1.0)),
           "length": float(base.get("pipe_len_m", 1.0)),
           "gamma": None, "grid": None}
    if parser.has_section("beam_info"):
        b = parser["beam_info"]
        if "gammarel" in b:
            out["gamma"] = float(b["gammarel"])
    if parser.has_section("frequency_info"):
        f = parser["frequency_info"]
        if "fmin" in f and "fmax" in f:
            fmin, fmax = float(f["fmin"]), float(f["fmax"])
            fstep = float(f.get("fstep", 2))
            n_pts = int(round((fmax - fmin) * (10 ** fstep))) + 1
            out["grid"] = {"frequency": {"min": 10.0 ** fmin, "max": 10.0 ** fmax,
                                         "n": n_pts, "log": True}}
    return out
