"""Writer for pytlwall-chamber-style .cfg files.

WIMBA builds pytlwall inputs in memory (Chamber/Layer/Beam via the API); for
debugging, every distinct geometry used in a run is also dumped as a readable
.cfg under <output>/pytlwall_inputs/. The chamber is written exactly as WIMBA
evaluates it: unit length and beta = 1 (per-assignment scaling by L and beta is
applied by WIMBA afterwards).
"""
from __future__ import annotations

from pathlib import Path


def _layer_lines(idx_or_name, lay):
    head = f"[{idx_or_name}]"
    thick = lay.get("thickness", lay.get("thick_m", ""))
    lines = [head,
             f"type = {lay.get('type', 'CW')}",
             f"thick_m = {thick}"]
    sigma = lay.get("sigma", lay.get("sigmaDC"))
    if sigma is not None:
        lines.append(f"sigmaDC = {sigma}")
    for src, dst in (("muinf_Hz", "muinf_Hz"), ("k_Hz", "k_Hz"),
                     ("epsr", "epsr"), ("tau", "tau"), ("RQ", "RQ")):
        if src in lay:
            lines.append(f"{dst} = {lay[src]}")
    return lines


def write_chamber_cfg(path, geometry, gamma=7000.0, length_m=1.0) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    layers = list(geometry.get("layers") or [])
    body = [f for f in layers if not f.get("boundary")]
    boundary = next((f for f in layers if f.get("boundary")), None)

    lines = [
        "; pytlwall chamber input generated by WIMBA (debug dump).",
        "; Evaluated at unit length and beta = 1; WIMBA scales each assignment",
        "; by its own length and local beta afterwards.",
        "",
        "[base_info]",
    ]
    if geometry.get("name"):
        lines.append(f"component_name = {geometry['name']}")
    lines += [f"chamber_shape = {geometry.get('shape', 'CIRCULAR')}",
              f"pipe_len_m = {length_m}",
              f"pipe_rad_m = {geometry.get('radius')}"]
    if geometry.get("hor") is not None:
        lines.append(f"pipe_hor_m = {geometry['hor']}")
    if geometry.get("ver") is not None:
        lines.append(f"pipe_ver_m = {geometry['ver']}")
    lines += ["betax = 1.0", "betay = 1.0", "",
              "[layers_info]", f"nbr_layers = {len(body)}", ""]
    for i, lay in enumerate(body):
        lines += _layer_lines(f"layer{i}", lay) + [""]
    if boundary is not None:
        lines += _layer_lines("boundary", boundary) + [""]
    lines += ["[beam_info]", f"gammarel = {gamma}", ""]
    path.write_text("\n".join(lines))
    return path
